import { Reading } from '../../../../types';
import {
  getMomentDate, GESTATIONAL_AGE_UNITS, INITIAL_URINE_TESTS,
} from '../../../utils';

export const createReading = ({
  readingId,
  dateTimeTaken,
  bpDiastolic,
  bpSystolic,
  heartRateBPM,
  symptoms,
  trafficLightStatus,
  isReferred,
  dateReferred,
  drugHistory,
  medicalHistory,
  urineTests,
}: any): any => {
  return {
    readingId,
    dateTimeTaken,
    bpDiastolic,
    bpSystolic,
    heartRateBPM,
    symptoms,
    trafficLightStatus,
    isReferred,
    dateReferred,
    drugHistory,
    medicalHistory,
    urineTests,
  };
};

export const sortReadings = (readings: Array<Reading>): Array<Reading> =>
  readings.sort((reading: Reading, otherReading: Reading) =>
    getMomentDate(otherReading.dateTimeTaken).valueOf() -
    getMomentDate(reading.dateTimeTaken).valueOf()
  );

export interface IState {
  displayPatientModal: boolean,
  selectedPatient: {
    readings: any,
    patientName: string,
    patientId: string,
    dob: string,
    patientAge: string,
    patientSex: string,
    isPregnant: boolean,
    gestationalAgeValue: string,
    gestationalAgeUnit: any,
    drugHistory: string,
    medicalHistory: string,
    bpSystolic: string,
    bpDiastolic: string,
    heartRateBPM: string,
  },
  patient: string,
  showVitals: boolean,
  showTrafficLights: boolean,
  displayReadingModal: boolean,
  newReading: {
    userId: string,
    readingId: string,
    dateTimeTaken: string,
    bpSystolic: string,
    bpDiastolic: string,
    heartRateBPM: string,
    dateRecheckVitalsNeeded: string,
    isFlaggedForFollowup: boolean,
    symptoms: string,
    urineTests: any,
  },
  checkedItems: {
    none: boolean,
    headache: boolean,
    bleeding: boolean,
    blurredVision: boolean,
    feverish: boolean,
    abdominalPain: boolean,
    unwell: boolean,
    other: boolean,
    otherSymptoms: string,
  },
  showSuccessReading: boolean,
  selectedPatientCopy: { readings: any },
  hasUrineTest: boolean,
  reset: boolean,
}

export const initialState: IState = {
  displayPatientModal: false,
  selectedPatient: {
    readings: [],
    patientName: ``,
    patientId: ``,
    dob: ``,
    patientAge: ``,
    patientSex: ``,
    isPregnant: false,
    gestationalAgeValue: ``,
    gestationalAgeUnit: GESTATIONAL_AGE_UNITS.WEEKS,
    drugHistory: ``,
    medicalHistory: ``,
    bpSystolic: ``,
    bpDiastolic: ``,
    heartRateBPM: ``,
  },
  patient: ``,
  showVitals: true,
  showTrafficLights: false,
  displayReadingModal: false,
  newReading: {
    userId: '',
    readingId: '',
    dateTimeTaken: '',
    bpSystolic: '',
    bpDiastolic: '',
    heartRateBPM: '',
    dateRecheckVitalsNeeded: '',
    isFlaggedForFollowup: false,
    symptoms: '',
    urineTests: INITIAL_URINE_TESTS,
  },
  checkedItems: {
    none: true,
    headache: false,
    bleeding: false,
    blurredVision: false,
    feverish: false,
    abdominalPain: false,
    unwell: false,
    other: false,
    otherSymptoms: '',
  },
  showSuccessReading: false,
  selectedPatientCopy: { readings: [] },
  hasUrineTest: false,
  reset: false,
};
