FORM_TEMPLATE_ROW_LENGTH = 16

FORM_TEMPLATE_NAME_ROW = 0
FORM_TEMPLATE_NAME_COL = 1

FORM_TEMPLATE_LANGUAGES_ROW = 0
FORM_TEMPLATE_LANGUAGES_COL = 3

FORM_TEMPLATE_VERSION_ROW = 1
FORM_TEMPLATE_VERSION_COL = 1

FORM_TEMPLATE_QUESTION_ID_COL = 0
FORM_TEMPLATE_QUESTION_TEXT_COL = 1
FORM_TEMPLATE_QUESTION_TYPE_COL = 2
FORM_TEMPLATE_QUESTION_LANG_COL = 3
FORM_TEMPLATE_QUESTION_REQUIRED_COL = 4
FORM_TEMPLATE_QUESTION_UNITS_COL = 5
FORM_TEMPLATE_QUESTION_VISIBILITY_CONDITION_COL = 6
FORM_TEMPLATE_QUESTION_MIN_VALUE_COL = 7
FORM_TEMPLATE_QUESTION_MAX_VALUE_COL = 8
FORM_TEMPLATE_QUESTION_LINE_COUNT_COL = 9
FORM_TEMPLATE_QUESTION_OPTIONS_COL = 10
