#################################################
# Docker file for defining services for testing #
# It includes the following containers:         #
#  - MySQL (For use as a mock database for      #
#          Backend API Tests)                   #
#################################################

services:

    mysql-test:
        container_name: cradle_mysql_test_db
        platform: linux/x86_64
        image: mysql:5.7
        volumes:
          - mysql_test_data:/var/lib/mysql
        profiles:
            -   test_mysql

        networks:
            - cradle_network
        environment:
            MYSQL_DATABASE: testing_cradle
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            start_period: 5s
            interval: 2s
            timeout: 5s
            retries: 20

        ports:
            - "3307:3306"

networks:
    cradle_network:
        external: true

volumes:
    mysql_test_data: