export const Endpoints = {
  PATIENT: `/patient`,
  PATIENTS: `/patients`,
  PATIENTS_ALL_INFO: `/patient/allinfo`,
  PATIENTS_GLOBAL_SEARCH: `/patient/global`,
  REFERRAL: `/referral`,
  PATIENT_FACILITY: `/patient/facility`,
  FOLLOW_UP: `/follow_up`,
  HEALTH_FACILITY_LIST: `/health_facility_list`,
  STATS: `/stats`,
  USER: `/user`,
  REGISTER: `/register`,
  AUTH: `/auth`,
  ALL: `/all`,
  VHTS: `/vhts`,
  EDIT: `/edit`,
  DELETE: `/delete`,
  READING: `/reading`,
  REFRESH: `/refresh_token`,
  CURRENT: `/current`,
};
