export enum EndpointEnum {
  ASSESSMENTS = '/assessments',
  ASSESSMENT_UPDATE = '/assessmentUpdate',
  DELETE = '/delete',
  EDIT = '/edit',
  HEALTH_FACILITY_LIST = '/facilities?simplified=true',
  HEALTH_FACILITIES = '/facilities',
  PATIENTS = '/patients',
  PATIENT_INFO = '/info' /* /patients/{PATIENT_ID}/info */,
  PATIENT_ASSOCIATIONS = '/patientAssociations',
  REFERRALS = '/referrals',
  READINGS = '/readings',
  STATISTICS = '/stats',
  STATS_ALL = '/stats/all',
  STATS_FACILITY = '/stats/facility',
  STATS_USER = '/stats/user',
  REGISTER = '/register',
  ALL_VHTS = '/user/vhts',
  AUTH = '/user/auth',
  REFRESH = '/user/auth/refresh_token',
  USER = '/user/',
  USER_ALL = '/user/all',
  USER_CURRENT = '/user/current',
  USER_REGISTER = '/user/register',
  VHTS = '/vhts',
  CHANGE_PASS = '/user/current/change_pass',
  RESET_PASS = '/change_pass',
}

export enum MethodEnum {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
}
