describe('Form templates', () => {
  beforeEach(() => {
    cy.login({ email: 'admin123@admin.com', password: 'admin123' })
  });
  it('simple form', () => {
    cy.visit('http://localhost:3000/admin/form-templates')
    cy.get('[data-testid="AddIcon"]').click()
    cy.url().should('include', '/admin/form-templates/new')
    cy.contains('.MuiOutlinedInput-root', 'Title').type("Dinner Party Form")
    cy.contains('.MuiOutlinedInput-root', 'Version').type("1")

    cy.get('.MuiButton-contained').contains('Add Field').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').type('Dietary')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').type("1")
    cy.get('.MuiButton-contained').contains('Save').click()

    cy.get('.MuiButton-contained').contains('Add Field').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').type('Any dietary restrictions?')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').type("2")
    cy.get('.MuiFormControlLabel-label').contains('Multi Select').click()
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').type('Vegeterian')
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').type('Vegan')
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 3').type('Kosher')
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 4').type('Halal')
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 5').type('Other')
    cy.get('.MuiButton-contained').contains('Save').click()

    cy.get('.MuiButton-contained').contains('Add Field').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').type('Please specify other dietary restriction')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').type("3")
    cy.get('.MuiFormControlLabel-label').contains('Text').click()
    cy.get('.MuiSwitch-input').click()
    cy.get(':nth-child(3) > .MuiGrid-root > :nth-child(6) > .MuiTypography-root').click()
    cy.get('.MuiButton-contained').contains('Save').click()

    cy.get('.MuiButton-contained').contains('Add Field').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').type('Any allergies?')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').type("4")
    cy.get('.MuiFormControlLabel-label').contains('Multiple Choice').click()
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').type('Yes')
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').type('No')
    cy.get('.MuiButton-contained').contains('Save').click()

    // Make a duplicate question and delete the original
    cy.get('.MuiButton-contained').contains('Add Field').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').type('Any allergies?')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').type("5")
    cy.get('.MuiFormControlLabel-label').contains('Multiple Choice').click()
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').type('Yes')
    cy.get('.MuiButton-contained').contains('Add Option').click()
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').type('No')
    cy.get('.MuiButton-contained').contains('Save').click()
    cy.get('[data-testid="DeleteIcon"]').eq(3).click()

    // Test edit and cancel
    cy.get('[data-testid="EditIcon"]').last().click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').should('contain', 'Any allergies?')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').should('contain', '5')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').clear()
    cy.contains('.MuiOutlinedInput-root', 'Question ID').type('4')
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').should('contain', 'Yes')
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').should('contain', 'No')
    cy.get(':nth-child(5) > .MuiFormGroup-root > :nth-child(1)').contains('Category').click({force: true})
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').should('not.exist')
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').should('not.exist')
    cy.get('.MuiButton-text').contains('Cancel').click()

    // Actually edit the field this time
    cy.get('[data-testid="EditIcon"]').last().click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').should('contain', 'Any allergies?')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').should('contain', '5')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').clear()
    cy.contains('.MuiOutlinedInput-root', 'Question ID').type('4')
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').should('contain', 'Yes')
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').should('contain', 'No')
    cy.get('.MuiButton-contained').contains('Save').click()

    // submit form and verify
    cy.get('.MuiGrid-container > .MuiButtonBase-root').contains('Submit Template').click()
    cy.get('.MuiDialogActions-root > .MuiButton-contained').contains('Submit').click()
    cy.get('[data-testid="ChevronLeftIcon"]').click()
    .wait(1000)
    cy.get('.MuiTableBody-root').contains('Dinner Party Form').siblings().children().find('[data-testid="EditIcon"]').click()
    cy.contains('.MuiOutlinedInput-root', 'Title').children('.MuiOutlinedInput-input').should('have.value', "Dinner Party Form")
    cy.contains('.MuiOutlinedInput-root', 'Version').children('.MuiOutlinedInput-input').should('have.value',"1")
    cy.contains('.MuiOutlinedInput-root', 'Language').children('.MuiOutlinedInput-input').should('have.value',"English")
    cy.contains('.MuiOutlinedInput-root', 'Language').children('.MuiOutlinedInput-input').should('have.value',"English")
    cy.get('.MuiGrid-grid-xs-11 > .MuiTypography-root').should('contain', 'Dietary')
    // validate the editfield
    cy.get(':nth-child(2) > :nth-child(2) > .MuiButtonBase-root > [data-testid="EditIcon"]').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').should('contain', 'Dietary')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').should('contain', '1')
    cy.get("input[name='field-type-group']").eq(0).should('be.checked').and('have.value', 'category')
    cy.get('.MuiButton-text').contains('Cancel').click()

    cy.get(':nth-child(4) > .MuiFormLabel-root > .MuiTypography-root').should('contain', 'Any dietary restrictions?')
    cy.get(':nth-child(2) > .MuiTypography-root').should('contain', 'Vegeterian')
    cy.get(':nth-child(3) > .MuiTypography-root').should('contain', 'Vegan')
    cy.get(':nth-child(4) > .MuiTypography-root').should('contain', 'Kosher')
    cy.get(':nth-child(5) > .MuiTypography-root').should('contain', 'Halal')
    cy.get(':nth-child(6) > .MuiTypography-root').should('contain', 'Other')
    // validate the editfield
    cy.get(':nth-child(5) > :nth-child(2) > .MuiButtonBase-root > [data-testid="EditIcon"]').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').should('contain', 'Any dietary restrictions?')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').should('contain', '2')
    cy.get("input[name='field-type-group']").eq(4).should('be.checked').and('have.value', 'mult_select')
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').should('contain', 'Vegeterian')
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').should('contain', 'Vegan')
    cy.contains('.MuiOutlinedInput-root', 'English Option 3').should('contain', 'Kosher')
    cy.contains('.MuiOutlinedInput-root', 'English Option 4').should('contain', 'Halal')
    cy.contains('.MuiOutlinedInput-root', 'English Option 5').should('contain', 'Other')
    cy.get('.MuiButton-text').contains('Cancel').click()

    cy.get('.MuiGrid-grid-sm-11 > .MuiFormControl-root > .MuiInputBase-root').should('contain', 'Please specify other dietary restriction')
    // validate the editfield
    cy.get(':nth-child(8) > :nth-child(2) > .MuiButtonBase-root > [data-testid="EditIcon"]').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').should('contain', 'Please specify other dietary restriction')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').should('contain', '3')
    cy.get("input[name='field-type-group']").eq(2).should('be.checked').and('have.value', 'text')
    cy.get(':nth-child(1) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').should('contain', 'Any dietary restrictions?')
    cy.get(':nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').should('contain', 'Equal to')
    // bug: other should be selected
    cy.get('.MuiButton-text').contains('Cancel').click()

    cy.get('#question_3 > .MuiTypography-root').should('contain', 'Any allergies?')
    cy.get('.MuiFormGroup-root > :nth-child(1) > .MuiTypography-root').should('contain', 'Yes')
    cy.get('.MuiFormGroup-root > :nth-child(2) > .MuiTypography-root').should('contain', 'No')
    // validate the editfield
    cy.get(':nth-child(11) > :nth-child(2) > .MuiButtonBase-root > [data-testid="EditIcon"]').click()
    cy.contains('.MuiOutlinedInput-root', 'Field Text').should('contain', 'Any allergies?')
    cy.contains('.MuiOutlinedInput-root', 'Question ID').should('contain', '4')
    cy.get("input[name='field-type-group']").eq(3).should('be.checked').and('have.value', 'mult_choice')
    cy.contains('.MuiOutlinedInput-root', 'English Option 1').should('contain', 'Yes')
    cy.contains('.MuiOutlinedInput-root', 'English Option 2').should('contain', 'No')
    cy.get('.MuiButton-text').contains('Cancel').click()
  });
});
