#!/bin/bash

# Exit immediately upon any failed command
set -e

echo "Deleting and receating the MySQL database..."
echo "You will be prompted for your MySQL root password."
mysql -u root -p -e"DROP DATABASE cradle; CREATE DATABASE cradle;"

echo "Creating the tables..."
python3 -m flask db upgrade

echo "Seeding the initial user information..."
python3 manage.py seed

echo "Done."

