#!/bin/bash

# Exit immediately upon any failed command
set -e

echo "Deleting and receating the MySQL database..."
echo "You will be prompted for your MySQL root password."
python3 manage.py reset_db

echo "Creating the tables..."
python3 -m flask db upgrade

echo "Seeding the initial user information..."
python3 manage.py seed

echo "Done."

