# This is a configuration file for Ruff, a Python linter. Only overriden options are present in this file

# Exclude a variety of commonly ignored directories.
exclude = [

]

target-version = "py39"

[lint]
# Enable all lint rules by default and specifically ignore those we do not want to use.
select = ["ALL"]

ignore = [
    # Disable conflicting rules
    "D211", # `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible
    "D212", # `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible.

    "E712", # SQLAlchemy uses `==` overrides so `a == False` is valid code in CRADLE
    "E711" # SQLAlchemy uses `==` overrides so `a == None` is valid code in CRADLE
]
