# This is a configuration file for Ruff, a Python linter. Only overriden options are present in this file

# Exclude a variety of commonly ignored directories.
exclude = [

]

target-version = "py39"

# # Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# # Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# # McCabe complexity (`C901`) by default.
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "I", # Sort imports - CRADLE
    "W"  # Pycodestyle - CRADLE
]

ignore = [
    "E712", # SQLAlchemy uses `==` overrides so `a == False` is valid code in CRADLE
    "E711" # SQLAlchemy uses `==` overrides so `a == None` is valid code in CRADLE
]
