#!/bin/bash

cd "$(dirname "$0")" || return
BASE_URL="$(./base-url)"

if [ $# -ge 1 ] ; then
    curl \
      --include \
      --request PUT  \
      --header "Content-Type: application/json" \
      --data '{"reading":"1", "referral":"2", "fillout":"3"}' \
      "$BASE_URL"/patient/"$1"
else
    echo "Usage: ./update-patient-info id"
fi
