#!/bin/bash

cd "$(dirname "$0")" || return
BASE_URL="$(./base-url)"

UUID=$(uuidgen)

curl \
  --include \
  --request POST  \
  --header "Content-Type: application/json" \
  --data '
{
  "patient": {
    "patientId": "'"$UUID"'",
    "patientAge": 30,
    "patientSex": "M"
  }
}' \
  "$BASE_URL"/patient