#!/bin/bash

cd "$(dirname "$0")" || return
BASE_URL="$(./base-url)"

curl \
  --include \
  --request POST  \
  --header "Content-Type: application/json" \
  --data '
{
  "personal-info": {
    "age": 30,
    "sex": "M",
    "medical_history": "None",
    "drug_history": "None",
    "pregnant": "Y",
    "symptoms": "None",
    "gestationalAge": "10",
    "village_no": "12",
    "village": null
  }
}' \
  "$BASE_URL"/patient