#!/bin/bash

cd "$(dirname "$0")" || return
BASE_URL="$(./base-url)"

if [ $# -ge 1 ] ; then
    curl \
      --include \
      --request GET  \
      --header "Content-Type: application/json" \
      "$BASE_URL"/patient/"$1"
else
    echo "Usage: ./get-patient id"
fi
