#!/bin/bash

cd "$(dirname "$0")" || return
BASE_URL="$(./base-url)"

if [ $# -ge 1 ] ; then
    curl \
      --include \
      --request PUT  \
      --header "Content-Type: application/json" \
      --data '
{
  "reading": {
    "readingId": "UUIDDR!#R#!",
    "dateLastSaved": "2019-09-25T19:00:43.002-07:00[America/Vancouver]",
    "pathToPhoto": "/storage/emulated/0/Pictures/CradleSupportApp/IMG_20190925_190031.jpg",
    "bpSystolic": 45,
    "bpDiastolic": 45,
    "heartRateBPM": 45,
    "dateTimeTaken": "2019-09-25T19:00:16.683-07:00[America/Vancouver]",
    "gpsLocationOfReading": null,
    "dateUploadedToServer": null,
    "dateRecheckVitalsNeeded": "2019-09-25T19:15:38.032-07:00[America/Vancouver]",
    "isFlaggedForFollowup": false,
    "referralMessageSendTime": null,
    "referralHealthCentre": null,
    "referralComment": null,
    "appVersion": "16 = Beta 0.016",
    "deviceInfo": "Google, Android SDK built for x86",
    "totalOcrSeconds": 0.0,
    "manuallyChangeOcrResults": 7,
    "temporaryFlags": 0,
    "userHasSelectedNoSymptoms": false
  },
  "referral": {
  },
  "fillout": {
  }
}' \
      "$BASE_URL"/patient/"$1"
else
    echo "Usage: ./update-patient-info id"
fi
