"""add past and future date booleans

Revision ID: 06022d85bf17
Revises: bef7a571db37
Create Date: 2024-02-13 07:51:54.408105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06022d85bf17"
down_revision = "bef7a571db37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("futureDates", sa.Boolean(), nullable=False))
    op.add_column("question", sa.Column("pastDates", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "pastDates")
    op.drop_column("question", "futureDates")
    # ### end Alembic commands ###
