"""empty message

Revision ID: 0f5578c0f6bb
Revises: 
Create Date: 2019-09-27 17:32:51.693795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5578c0f6bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followUp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followUpAction', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('healthFacility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('VHT', 'HCW', 'ADMIN', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('village',
    sa.Column('villageNumber', sa.String(length=50), nullable=False),
    sa.Column('zoneNumber', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('villageNumber')
    )
    op.create_table('patient',
    sa.Column('patientId', sa.String(length=50), nullable=False),
    sa.Column('patientName', sa.String(length=50), nullable=True),
    sa.Column('patientAge', sa.Integer(), nullable=False),
    sa.Column('patientSex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sexenum'), nullable=False),
    sa.Column('isPregnant', sa.Boolean(), nullable=True),
    sa.Column('gestationalAgeUnit', sa.String(length=50), nullable=True),
    sa.Column('gestationalAgeValue', sa.String(length=20), nullable=True),
    sa.Column('medicalHistory', sa.Text(), nullable=True),
    sa.Column('drugHistory', sa.Text(), nullable=True),
    sa.Column('villageNumber', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['villageNumber'], ['village.villageNumber'], ),
    sa.PrimaryKeyConstraint('patientId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('healthFacilityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['healthFacilityId'], ['healthFacility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('reading',
    sa.Column('readingId', sa.Integer(), nullable=False),
    sa.Column('bpSystolic', sa.Integer(), nullable=True),
    sa.Column('bpDiastolic', sa.Integer(), nullable=True),
    sa.Column('heartRateBPM', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('dateLastSaved', sa.String(length=100), nullable=True),
    sa.Column('dateTimeTaken', sa.String(length=100), nullable=True),
    sa.Column('dateUploadedToServer', sa.String(length=100), nullable=True),
    sa.Column('dateRecheckVitalsNeeded', sa.String(length=100), nullable=True),
    sa.Column('gpsLocationOfReading', sa.String(length=50), nullable=True),
    sa.Column('retestOfPreviousReadingIds', sa.String(length=100), nullable=True),
    sa.Column('isFlaggedForFollowup', sa.Boolean(), nullable=True),
    sa.Column('appVersion', sa.String(length=50), nullable=True),
    sa.Column('deviceInfo', sa.String(length=50), nullable=True),
    sa.Column('totalOcrSeconds', sa.Float(), nullable=True),
    sa.Column('manuallyChangeOcrResults', sa.Integer(), nullable=True),
    sa.Column('temporaryFlags', sa.Integer(), nullable=True),
    sa.Column('userHasSelectedNoSymptoms', sa.Boolean(), nullable=True),
    sa.Column('patientId', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patient.patientId'], ),
    sa.PrimaryKeyConstraint('readingId')
    )
    op.create_table('userRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('roleId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roleId'], ['role.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateReferred', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('patientId', sa.String(length=50), nullable=True),
    sa.Column('referralHealthFacilityId', sa.Integer(), nullable=True),
    sa.Column('readingId', sa.Integer(), nullable=True),
    sa.Column('followUpId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followUpId'], ['followUp.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patient.patientId'], ),
    sa.ForeignKeyConstraint(['readingId'], ['reading.readingId'], ),
    sa.ForeignKeyConstraint(['referralHealthFacilityId'], ['healthFacility.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    op.drop_table('userRole')
    op.drop_table('reading')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('patient')
    op.drop_table('village')
    op.drop_table('role')
    op.drop_table('healthFacility')
    op.drop_table('followUp')
    # ### end Alembic commands ###
