"""decouple referrals from readings

Revision ID: 1029b5bb3354
Revises: c2df1dcd9256
Create Date: 2022-02-02 02:40:55.334510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1029b5bb3354"
down_revision = "daacd2c90e9e"
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral", sa.Column("dateAssessedBackUp", sa.BigInteger(), nullable=True)
    )
    connection.execute(
        (
            "UPDATE referral r "
            "INNER JOIN followup f "
            "ON r.readingId = f.readingId "
            "SET r.dateAssessedBackUp = f.dateAssessed "
        )
    )
    op.drop_constraint("referral_ibfk_3", "referral", type_="foreignkey")
    op.drop_column("referral", "readingId")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral", sa.Column("readingId", mysql.VARCHAR(length=50), nullable=True)
    )
    op.create_foreign_key(
        "referral_ibfk_3", "referral", "reading", ["readingId"], ["readingId"]
    )
    op.drop_column("referral", "dateAssessedBackUp")
    # ### end Alembic commands ###
