"""
Add missing attributes and foreign keys to workflow instances and steps

Revision ID: 10_dcbe6ac27ffb
Revises: 9_54251029538f
Create Date: 2025-06-19 00:16:49.341976

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10_dcbe6ac27ffb"
down_revision = "9_54251029538f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_instance", sa.Column("name", sa.String(length=200), nullable=False))
    op.add_column("workflow_instance", sa.Column("title", sa.Text(), nullable=False))
    op.add_column("workflow_instance", sa.Column("current_step_id", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_workflow_instance_name"), "workflow_instance", ["name"], unique=False)
    op.add_column("workflow_instance_step", sa.Column("name", sa.String(length=200), nullable=False))
    op.add_column("workflow_instance_step", sa.Column("title", sa.Text(), nullable=False))
    op.add_column("workflow_instance_step", sa.Column("triggered_by", sa.String(length=50), nullable=True))
    op.add_column("workflow_instance_step", sa.Column("condition_id", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_workflow_instance_step_name"), "workflow_instance_step", ["name"], unique=False)
    op.create_foreign_key(op.f("fk_workflow_instance_step_condition_id_rule_group"), "workflow_instance_step", "rule_group", ["condition_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_workflow_instance_step_condition_id_rule_group"), "workflow_instance_step", type_="foreignkey")
    op.drop_index(op.f("ix_workflow_instance_step_name"), table_name="workflow_instance_step")
    op.drop_column("workflow_instance_step", "condition_id")
    op.drop_column("workflow_instance_step", "triggered_by")
    op.drop_column("workflow_instance_step", "title")
    op.drop_column("workflow_instance_step", "name")
    op.drop_index(op.f("ix_workflow_instance_name"), table_name="workflow_instance")
    op.drop_column("workflow_instance", "current_step_id")
    op.drop_column("workflow_instance", "title")
    op.drop_column("workflow_instance", "name")
    # ### end Alembic commands ###
