"""Add new relationships between workflow components and other models

Revision ID: 11_3825d1e505de
Revises: 10_dcbe6ac27ffb
Create Date: 2025-06-21 09:13:53.874112

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "11_3825d1e505de"
down_revision = "10_dcbe6ac27ffb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template_step_branch",
        sa.Column("condition_id", sa.String(length=50), nullable=True),
    )
    op.drop_constraint(
        "fk_workflow_template_step_branch_condition_rule_group",
        "workflow_template_step_branch",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_workflow_template_step_branch_condition_id_rule_group"),
        "workflow_template_step_branch",
        "rule_group",
        ["condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workflow_template_step_branch", "condition")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template_step_branch",
        sa.Column("condition", mysql.VARCHAR(length=50), nullable=True),
    )
    op.drop_constraint(
        op.f("fk_workflow_template_step_branch_condition_id_rule_group"),
        "workflow_template_step_branch",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_workflow_template_step_branch_condition_rule_group",
        "workflow_template_step_branch",
        "rule_group",
        ["condition"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workflow_template_step_branch", "condition_id")
    # ### end Alembic commands ###
