"""
Fix target_step_id in template step branch model to string instead of int

Revision ID: 12_11b10f40456a
Revises: 11_3825d1e505de
Create Date: 2025-07-06 05:10:04.395633

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "12_11b10f40456a"
down_revision = "11_3825d1e505de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_template_step_branch",
        "target_step_id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_template_step_branch",
        "target_step_id",
        existing_type=sa.String(length=50),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
