"""
Add attribute to WorkflowTemplateOrm for the starting step ID, make target_step_id in WorkflowTemplateStepBranchOrm nullable

Revision ID: 13_b6ff0a713e0e
Revises: 12_11b10f40456a
Create Date: 2025-07-10 23:57:29.297182

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "13_b6ff0a713e0e"
down_revision = "12_11b10f40456a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template",
        sa.Column("starting_step_id", sa.String(length=50), nullable=True),
    )
    op.alter_column(
        "workflow_template_step_branch",
        "target_step_id",
        existing_type=mysql.VARCHAR(length=50),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_template_step_branch",
        "target_step_id",
        existing_type=mysql.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_column("workflow_template", "starting_step_id")
    # ### end Alembic commands ###
