"""
Change 'title' attribute to 'description', remove 'last_edited_by' fields in workflow template components, make 'form_id' nullable in template steps

Revision ID: 15_bf923c5cb3c3
Revises: 13_b6ff0a713e0e
Create Date: 2025-07-31 00:42:59.525474

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "15_bf923c5cb3c3"
down_revision = "14_ba9e8dbc95de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_workflow_template_last_edited_by_user",
        "workflow_template",
        type_="foreignkey",
    )
    op.drop_column("workflow_template", "last_edited_by")
    op.add_column(
        "workflow_template_step", sa.Column("description", sa.Text(), nullable=False)
    )
    op.alter_column(
        "workflow_template_step",
        "form_id",
        existing_type=mysql.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_constraint(
        "fk_workflow_template_step_last_edited_by_user",
        "workflow_template_step",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_workflow_template_step_form_id_form_template",
        "workflow_template_step",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_workflow_template_step_form_id_form_template"),
        "workflow_template_step",
        "form_template",
        ["form_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workflow_template_step", "title")
    op.drop_column("workflow_template_step", "last_edited_by")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template_step",
        sa.Column(
            "last_edited_by",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "workflow_template_step", sa.Column("title", mysql.TEXT(), nullable=False)
    )
    op.drop_constraint(
        op.f("fk_workflow_template_step_form_id_form_template"),
        "workflow_template_step",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_workflow_template_step_form_id_form_template",
        "workflow_template_step",
        "form_template",
        ["form_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_workflow_template_step_last_edited_by_user",
        "workflow_template_step",
        "user",
        ["last_edited_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "workflow_template_step",
        "form_id",
        existing_type=mysql.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_column("workflow_template_step", "description")
    op.add_column(
        "workflow_template",
        sa.Column(
            "last_edited_by",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_workflow_template_last_edited_by_user",
        "workflow_template",
        "user",
        ["last_edited_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
