"""
Add last_edited field to workflow collection model

Revision ID: 17_864e4bd5280f
Revises: 16_40db9301f4d5
Create Date: 2025-08-13 07:39:36.283883

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "19_864e4bd5280f"
down_revision = "18_0520a90e0303"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_collection", sa.Column("last_edited", sa.BigInteger(), nullable=False)
    )
    op.create_index(
        op.f("ix_workflow_collection_name"),
        "workflow_collection",
        ["name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_collection_name"), table_name="workflow_collection")
    op.drop_column("workflow_collection", "last_edited")
    # ### end Alembic commands ###
