"""empty message

Revision ID: 1c55770c0c89
Revises: 8d5f29cfd165
Create Date: 2020-02-26 11:19:45.275082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c55770c0c89'
down_revision = '8d5f29cfd165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup', sa.Column('dateReviewNeeded', sa.Date(), nullable=True))
    op.add_column('followup', sa.Column('followupNeeded', sa.Boolean(), nullable=True))
    op.add_column('followup', sa.Column('medicationPrescribed', sa.Text(), nullable=True))
    op.add_column('followup', sa.Column('specialInvestigations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followup', 'specialInvestigations')
    op.drop_column('followup', 'medicationPrescribed')
    op.drop_column('followup', 'followupNeeded')
    op.drop_column('followup', 'dateReviewNeeded')
    # ### end Alembic commands ###
