"""empty message

Revision ID: 1de198f8daee
Revises: 107832ed8e9c
Create Date: 2019-09-20 22:18:37.275339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de198f8daee'
down_revision = '107832ed8e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follow_up_action', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('VHT', 'HCW', 'ADMIN', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('village',
    sa.Column('village_no', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('village_no')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sexenum'), nullable=False),
    sa.Column('pregnant', sa.Boolean(), nullable=True),
    sa.Column('gestationalAge', sa.String(length=20), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('drug_history', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('village_no', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['village_no'], ['village.village_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('date_time_taken', sa.DateTime(), nullable=True),
    sa.Column('date_uploaded_to_server', sa.DateTime(), nullable=True),
    sa.Column('gps_location_of_reading', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_referred', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('referral_health_facility_id', sa.Integer(), nullable=True),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_up.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], ),
    sa.ForeignKeyConstraint(['referral_health_facility_id'], ['health_facility.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('health_facility_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'health_facility', ['health_facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'health_facility_id')
    op.drop_table('referral')
    op.drop_table('user_role')
    op.drop_table('reading')
    op.drop_table('patient')
    op.drop_table('village')
    op.drop_table('role')
    op.drop_table('health_facility')
    op.drop_table('follow_up')
    # ### end Alembic commands ###
