"""
update form columns for workflow instances

Revision ID: 21_34bb66b2155f
Revises: 20_7edada0266e5
Create Date: 2025-10-16 02:12:40.027340

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21_34bb66b2155f"
down_revision = "20_7edada0266e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_instance_step",
        sa.Column("form_template_id", sa.String(length=50), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_workflow_instance_step_form_template_id_form_template"),
        "workflow_instance_step",
        "form_template",
        ["form_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workflow_instance_step_form_template_id_form_template"),
        "workflow_instance_step",
        type_="foreignkey",
    )
    op.drop_column("workflow_instance_step", "form_template_id")
    # ### end Alembic commands ###
