"""
Remove conditions on steps and workflows

Revision ID: 21_7b3f23d50a34
Revises: 20_7edada0266e5
Create Date: 2025-10-11 05:36:28.880888

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "21_7b3f23d50a34"
down_revision = "20_7edada0266e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_workflow_instance_step_condition_id_rule_group",
        "workflow_instance_step",
        type_="foreignkey",
    )
    op.drop_column("workflow_instance_step", "condition_id")
    op.drop_constraint(
        "fk_workflow_template_initial_condition_id_rule_group",
        "workflow_template",
        type_="foreignkey",
    )
    op.drop_column("workflow_template", "initial_condition_id")
    op.drop_constraint(
        "fk_workflow_template_step_condition_id_rule_group",
        "workflow_template_step",
        type_="foreignkey",
    )
    op.drop_column("workflow_template_step", "condition_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template_step",
        sa.Column("condition_id", mysql.VARCHAR(length=50), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflow_template_step_condition_id_rule_group",
        "workflow_template_step",
        "rule_group",
        ["condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "workflow_template",
        sa.Column("initial_condition_id", mysql.VARCHAR(length=50), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflow_template_initial_condition_id_rule_group",
        "workflow_template",
        "rule_group",
        ["initial_condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "workflow_instance_step",
        sa.Column("condition_id", mysql.VARCHAR(length=50), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflow_instance_step_condition_id_rule_group",
        "workflow_instance_step",
        "rule_group",
        ["condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
