"""Delete conditions and branches from workflows

Revision ID: 21_f6c922d3ae4b
Revises: 20_7edada0266e5
Create Date: 2025-10-03 17:58:31.278810

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "21_f6c922d3ae4b"
down_revision = "20_7edada0266e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_template_step_branch")
    op.drop_constraint(
        "fk_workflow_instance_step_condition_id_rule_group",
        "workflow_instance_step",
        type_="foreignkey",
    )
    op.drop_column("workflow_instance_step", "triggered_by")
    op.drop_column("workflow_instance_step", "condition_id")
    op.drop_constraint(
        "fk_workflow_template_initial_condition_id_rule_group",
        "workflow_template",
        type_="foreignkey",
    )
    op.drop_column("workflow_template", "initial_condition_id")
    op.drop_constraint(
        "fk_workflow_template_step_condition_id_rule_group",
        "workflow_template_step",
        type_="foreignkey",
    )
    op.drop_column("workflow_template_step", "condition_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template_step",
        sa.Column("condition_id", mysql.VARCHAR(length=50), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflow_template_step_condition_id_rule_group",
        "workflow_template_step",
        "rule_group",
        ["condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "workflow_template",
        sa.Column("initial_condition_id", mysql.VARCHAR(length=50), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflow_template_initial_condition_id_rule_group",
        "workflow_template",
        "rule_group",
        ["initial_condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "workflow_instance_step",
        sa.Column("condition_id", mysql.VARCHAR(length=50), nullable=True),
    )
    op.add_column(
        "workflow_instance_step",
        sa.Column("triggered_by", mysql.VARCHAR(length=50), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflow_instance_step_condition_id_rule_group",
        "workflow_instance_step",
        "rule_group",
        ["condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "workflow_template_step_branch",
        sa.Column("id", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("target_step_id", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("step_id", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("condition_id", mysql.VARCHAR(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["rule_group.id"],
            name="fk_workflow_template_step_branch_condition_id_rule_group",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["workflow_template_step.id"],
            name="fk_workflow_template_step_branch_step_id_workflow_template_step",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
