"""
add workflow template step id to workflow instance step

Revision ID: 22_298e59ec02b9
Revises: 21_7b3f23d50a34
Create Date: 2025-10-21 00:21:03.128913

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22_298e59ec02b9"
down_revision = "21_7b3f23d50a34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_instance_step",
        sa.Column("workflow_template_step_id", sa.String(length=50), nullable=True),
    )
    op.create_foreign_key(
        op.f(
            "fk_workflow_instance_step_workflow_template_step_id_workflow_template_step"
        ),
        "workflow_instance_step",
        "workflow_template_step",
        ["workflow_template_step_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f(
            "fk_workflow_instance_step_workflow_template_step_id_workflow_template_step"
        ),
        "workflow_instance_step",
        type_="foreignkey",
    )
    op.drop_column("workflow_instance_step", "workflow_template_step_id")
    # ### end Alembic commands ###
