"""
add form v2 tables

Revision ID: 23_89f6c4a8dc52
Revises: 22_298e59ec02b9
Create Date: 2025-11-04 05:56:48.404815

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23_89f6c4a8dc52"
down_revision = "22_298e59ec02b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_classification_v2",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name_string_id", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_classification_v2")),
    )
    op.create_index(
        op.f("ix_form_classification_v2_name_string_id"),
        "form_classification_v2",
        ["name_string_id"],
        unique=False,
    )
    op.create_table(
        "lang_version_v2",
        sa.Column("string_id", sa.String(length=50), nullable=False),
        sa.Column("lang", sa.String(length=50), nullable=False),
        sa.Column("text", sa.Text(collation="utf8mb4_general_ci"), nullable=False),
        sa.PrimaryKeyConstraint("string_id", "lang", name=op.f("pk_lang_version_v2")),
    )
    op.create_table(
        "form_template_v2",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("form_classification_id", sa.String(length=50), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("date_created", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_classification_id"],
            ["form_classification_v2.id"],
            name=op.f(
                "fk_form_template_v2_form_classification_id_form_classification_v2"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_template_v2")),
    )
    op.create_table(
        "form_question_template_v2",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("form_template_id", sa.String(length=50), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "INTEGER",
                "DECIMAL",
                "STRING",
                "MULTIPLE_CHOICE",
                "MULTIPLE_SELECT",
                "DATE",
                "TIME",
                "DATETIME",
                "CATEGORY",
                name="questiontypeenum",
            ),
            nullable=False,
        ),
        sa.Column("string_id", sa.String(length=50), nullable=False),
        sa.Column("mc_options", sa.Text(), nullable=True),
        sa.Column("user_question_id", sa.String(length=50), nullable=False),
        sa.Column("has_comment_attached", sa.Boolean(), nullable=False),
        sa.Column("category_index", sa.Integer(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("visible_condition", sa.Text(), nullable=False),
        sa.Column("units", sa.Text(), nullable=True),
        sa.Column("num_min", sa.Float(), nullable=True),
        sa.Column("num_max", sa.Float(), nullable=True),
        sa.Column("string_max_length", sa.Integer(), nullable=True),
        sa.Column("string_max_lines", sa.Integer(), nullable=True),
        sa.Column("allow_future_dates", sa.Boolean(), nullable=False),
        sa.Column("allow_past_dates", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_template_id"],
            ["form_template_v2.id"],
            name=op.f("fk_form_question_template_v2_form_template_id_form_template_v2"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_question_template_v2")),
    )
    op.create_index(
        op.f("ix_form_question_template_v2_form_template_id"),
        "form_question_template_v2",
        ["form_template_id"],
        unique=False,
    )
    op.create_table(
        "form_submission_v2",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("form_template_id", sa.String(length=50), nullable=True),
        sa.Column("patient_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date_submitted", sa.BigInteger(), nullable=False),
        sa.Column("last_edited", sa.BigInteger(), nullable=False),
        sa.Column("lang", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_template_id"],
            ["form_template_v2.id"],
            name=op.f("fk_form_submission_v2_form_template_id_form_template_v2"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
            name=op.f("fk_form_submission_v2_patient_id_patient"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_form_submission_v2_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_submission_v2")),
    )
    op.create_table(
        "form_answer_v2",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("question_id", sa.String(length=50), nullable=False),
        sa.Column("form_submission_id", sa.String(length=50), nullable=False),
        sa.Column("answer", sa.Text(collation="utf8mb4_general_ci"), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_submission_id"],
            ["form_submission_v2.id"],
            name=op.f("fk_form_answer_v2_form_submission_id_form_submission_v2"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["form_question_template_v2.id"],
            name=op.f("fk_form_answer_v2_question_id_form_question_template_v2"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_answer_v2")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_answer_v2")
    op.drop_table("form_submission_v2")
    op.drop_index(
        op.f("ix_form_question_template_v2_form_template_id"),
        table_name="form_question_template_v2",
    )
    op.drop_table("form_question_template_v2")
    op.drop_table("form_template_v2")
    op.drop_table("lang_version_v2")
    op.drop_index(
        op.f("ix_form_classification_v2_name_string_id"),
        table_name="form_classification_v2",
    )
    op.drop_table("form_classification_v2")
    # ### end Alembic commands ###
