"""
Allow start_date to be null for workflow instances, so start_date can be set when
the workflow and step actually start.

Revision ID: 23_cd83978bd585
Revises: 22_298e59ec02b9
Create Date: 2025-11-06 17:35:59.580284

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "23_cd83978bd585"
down_revision = "22_298e59ec02b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_instance",
        "start_date",
        existing_type=mysql.BIGINT(display_width=20),
        nullable=True,
    )
    op.alter_column(
        "workflow_instance_step",
        "start_date",
        existing_type=mysql.BIGINT(display_width=20),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_instance_step",
        "start_date",
        existing_type=mysql.BIGINT(display_width=20),
        nullable=False,
    )
    op.alter_column(
        "workflow_instance",
        "start_date",
        existing_type=mysql.BIGINT(display_width=20),
        nullable=False,
    )
    # ### end Alembic commands ###
