"""remove form template and user foreign key

Revision ID: 2435e7cc9c9c
Revises: 19f48b160991
Create Date: 2022-03-16 05:19:16.393868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2435e7cc9c9c'
down_revision = '19f48b160991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_form_user_last_edited_by_id', 'form', type_='foreignkey')
    op.drop_constraint('fk_form_form_template_form_template_id_id', 'form', type_='foreignkey')
    op.drop_column('form', 'lastEditedBy')
    op.drop_column('form', 'formTemplateId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('formTemplateId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('form', sa.Column('lastEditedBy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_form_form_template_form_template_id_id', 'form', 'form_template', ['formTemplateId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_form_user_last_edited_by_id', 'form', 'user', ['lastEditedBy'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
