"""Add workflow translation support

Revision ID: 25_19ce5d61fb20
Revises: 24_f277265972d3
Create Date: 2026-02-10 06:09:20.321549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25_19ce5d61fb20'
down_revision = '24_f277265972d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_classification', sa.Column('name_string_id', sa.String(length=50), nullable=False))
    op.drop_index('ix_workflow_classification_name', table_name='workflow_classification')
    op.create_index(op.f('ix_workflow_classification_name_string_id'), 'workflow_classification', ['name_string_id'], unique=False)
    op.drop_column('workflow_classification', 'name')
    op.drop_index('ix_workflow_instance_name', table_name='workflow_instance')
    op.drop_column('workflow_instance', 'name')
    op.drop_index('ix_workflow_instance_step_name', table_name='workflow_instance_step')
    op.drop_column('workflow_instance_step', 'name')
    op.drop_index('ix_workflow_template_name', table_name='workflow_template')
    op.drop_column('workflow_template', 'name')
    op.add_column('workflow_template_step', sa.Column('name_string_id', sa.String(length=50), nullable=True))
    op.drop_index('ix_workflow_template_step_name', table_name='workflow_template_step')
    op.create_index(op.f('ix_workflow_template_step_name_string_id'), 'workflow_template_step', ['name_string_id'], unique=False)
    op.drop_column('workflow_template_step', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_template_step', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.drop_index(op.f('ix_workflow_template_step_name_string_id'), table_name='workflow_template_step')
    op.create_index('ix_workflow_template_step_name', 'workflow_template_step', ['name'], unique=False)
    op.drop_column('workflow_template_step', 'name_string_id')
    op.add_column('workflow_template', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.create_index('ix_workflow_template_name', 'workflow_template', ['name'], unique=False)
    op.add_column('workflow_instance_step', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.create_index('ix_workflow_instance_step_name', 'workflow_instance_step', ['name'], unique=False)
    op.add_column('workflow_instance', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.create_index('ix_workflow_instance_name', 'workflow_instance', ['name'], unique=False)
    op.add_column('workflow_classification', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.drop_index(op.f('ix_workflow_classification_name_string_id'), table_name='workflow_classification')
    op.create_index('ix_workflow_classification_name', 'workflow_classification', ['name'], unique=False)
    op.drop_column('workflow_classification', 'name_string_id')
    # ### end Alembic commands ###
