"""
Restore name field to WorkflowInstance

Revision ID: 26_31497c6c8fe7
Revises: 25_19ce5d61fb20
Create Date: 2026-02-10 06:17:43.014160

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26_31497c6c8fe7"
down_revision = "25_19ce5d61fb20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_instance", sa.Column("name", sa.String(length=200), nullable=True)
    )
    op.create_index(
        op.f("ix_workflow_instance_name"), "workflow_instance", ["name"], unique=False
    )
    op.add_column(
        "workflow_instance_step",
        sa.Column("name", sa.String(length=200), nullable=True),
    )
    op.create_index(
        op.f("ix_workflow_instance_step_name"),
        "workflow_instance_step",
        ["name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_instance_step_name"), table_name="workflow_instance_step"
    )
    op.drop_column("workflow_instance_step", "name")
    op.drop_index(op.f("ix_workflow_instance_name"), table_name="workflow_instance")
    op.drop_column("workflow_instance", "name")
    # ### end Alembic commands ###
