"""Add name_string_id to workflow_template

Revision ID: 27_a3b5c7d9e1f2
Revises: 26_31497c6c8fe7
Create Date: 2026-02-10 07:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27_a3b5c7d9e1f2'
down_revision = '26_31497c6c8fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_template', sa.Column(
        'name_string_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_workflow_template_name_string_id'),
                    'workflow_template', ['name_string_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_template_name_string_id'),
                  table_name='workflow_template')
    op.drop_column('workflow_template', 'name_string_id')
    # ### end Alembic commands ###
