"""empty message

Revision ID: 2a8daaa2b9ac
Revises: b4263a7016f6
Create Date: 2020-02-22 12:41:38.616173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8daaa2b9ac'
down_revision = 'b4263a7016f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'dob')
    # ### end Alembic commands ###
