"""template change name type make index and unique

Revision ID: 2c7e8d1996af
Revises: 15ba72e0ecaa
Create Date: 2022-04-19 04:57:26.989578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c7e8d1996af'
down_revision = '15ba72e0ecaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_template', 'name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
    op.create_index(op.f('ix_form_template_name'), 'form_template', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_template_name'), table_name='form_template')
    op.alter_column('form_template', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
