"""associate follow up directly to reading

Revision ID: 30101cf360db
Revises: e5396a8c62db
Create Date: 2020-07-11 19:09:20.648049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "30101cf360db"
down_revision = "118564bd12f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "followup", sa.Column("readingId", sa.String(length=50), nullable=False)
    )
    op.create_foreign_key(None, "followup", "reading", ["readingId"], ["readingId"])
    op.drop_column("followup", "followupFrequencyValue")
    op.drop_column("followup", "followupFrequencyUnit")
    op.drop_column("followup", "dateFollowupNeededTill")
    op.add_column("referral", sa.Column("isAssessed", sa.Boolean(), nullable=False))
    op.drop_constraint("referral_ibfk_1", "referral", type_="foreignkey")
    op.drop_column("referral", "followUpId")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral",
        sa.Column(
            "followUpId",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "referral_ibfk_1", "referral", "followup", ["followUpId"], ["id"]
    )
    op.drop_column("referral", "isAssessed")
    op.add_column(
        "followup",
        sa.Column(
            "dateFollowupNeededTill",
            mysql.VARCHAR(collation="utf8mb4_general_ci", length=50),
            nullable=True,
        ),
    )
    op.add_column(
        "followup",
        sa.Column(
            "followupFrequencyUnit",
            mysql.ENUM(
                "MINUTES",
                "HOURS",
                "DAYS",
                "WEEKS",
                "MONTHS",
                "YEARS",
                collation="utf8mb4_general_ci",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "followup", sa.Column("followupFrequencyValue", mysql.FLOAT(), nullable=True)
    )
    op.drop_constraint(None, "followup", type_="foreignkey")
    op.drop_column("followup", "readingId")
    # ### end Alembic commands ###
