"""add allergy field to patient

Revision ID: 30_5c7f69c30f5e
Revises: 29_b744b32f117e
Create Date: 2021-06-14 07:04:40.033591

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "30_5c7f69c30f5e"
down_revision = "29_b744b32f117e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patient", sa.Column("allergy", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patient", "allergy")
    # ### end Alembic commands ###
