"""change form template id to string

Revision ID: 34a86324fdb4
Revises: c91d7f81c853
Create Date: 2022-03-22 05:56:47.644031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "34a86324fdb4"
down_revision = "c91d7f81c853"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    op.drop_constraint("question_ibfk_2", "question", type_="foreignkey")
    op.drop_constraint(
        "fk_form_form_template_form_template_id_id", "form", type_="foreignkey"
    )

    op.alter_column(
        "form_template",
        "id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint("PRIMARY", "form_template", type_="primary")
    op.alter_column(
        "question",
        "formTemplateId",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "form",
        "formTemplateId",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=50),
        existing_nullable=True,
    )

    connection.execute(f"DELETE FROM form_template")
    connection.execute(f"DELETE FROM question")
    connection.execute(f"DELETE FROM form")

    op.create_primary_key("pk_form_template", "form_template", ["id"])
    op.create_foreign_key(
        "question_ibfk_2",
        "question",
        "form_template",
        ["formTemplateId"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_form_form_template_form_template_id_id",
        "form",
        "form_template",
        ["formTemplateId"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    op.drop_constraint("question_ibfk_2", "question", type_="foreignkey")
    op.drop_constraint(
        "fk_form_form_template_form_template_id_id", "form", type_="foreignkey"
    )
    op.drop_constraint("PRIMARY", "form_template", type_="primary")

    connection.execute(f"DELETE FROM form_template")
    connection.execute(f"DELETE FROM question")
    connection.execute(f"DELETE FROM form")

    op.alter_column(
        "question",
        "formTemplateId",
        existing_type=sa.String(length=50),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=True,
    )
    op.alter_column(
        "form",
        "formTemplateId",
        existing_type=sa.String(length=50),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=True,
    )
    op.create_primary_key("pk_form_template", "form_template", ["id"])
    op.alter_column(
        "form_template",
        "id",
        existing_type=sa.String(length=50),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
        autoincrement=True,
    )

    op.create_foreign_key(
        "question_ibfk_2",
        "question",
        "form_template",
        ["formTemplateId"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_form_form_template_form_template_id_id",
        "form",
        "form_template",
        ["formTemplateId"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
