"""referral add assess and cancel relevant fields

Revision ID: 36_b62ebe3bee7a
Revises: 35_7ccbc75caff1
Create Date: 2022-02-12 07:19:33.491606

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36_b62ebe3bee7a"
down_revision = "35_7ccbc75caff1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("referral", sa.Column("dateAssessed", sa.BigInteger(), nullable=True))
    op.add_column("referral", sa.Column("isCancelled", sa.Boolean(), nullable=False))
    op.add_column(
        "referral", sa.Column("dateCancelled", sa.BigInteger(), nullable=True)
    )
    op.add_column("referral", sa.Column("cancelReason", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referral", "cancelReason")
    op.drop_column("referral", "dateCancelled")
    op.drop_column("referral", "isCancelled")
    op.drop_column("referral", "dateAssessed")
    # ### end Alembic commands ###
