"""
sms relay request number table

Revision ID: 3_f3f6a6a9a6f5
Revises: 2_b8282462d070
Create Date: 2025-02-21 02:04:38.489560

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3_f3f6a6a9a6f5"
down_revision = "2_b8282462d070"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_relay_request_number",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("expected_request_number", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_sms_relay_request_number_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_relay_request_number")),
        sa.UniqueConstraint(
            "user_id", name=op.f("uq_sms_relay_request_number_user_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sms_relay_request_number")
    # ### end Alembic commands ###
