"""change lang sensitive fields to new collation

Revision ID: 3b0691f5ce8e
Revises: 75cd2467e3e4
Create Date: 2022-04-09 08:27:16.623600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b0691f5ce8e"
down_revision = "75cd2467e3e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question",
        sa.Column(
            "questionText", sa.Text(collation="utf8mb4_general_ci"), nullable=False
        ),
    )
    op.add_column(
        "question",
        sa.Column("mcOptions", sa.Text(collation="utf8mb4_general_ci"), nullable=False),
    )
    op.add_column(
        "question_lang_version",
        sa.Column(
            "questionText", sa.Text(collation="utf8mb4_general_ci"), nullable=False
        ),
    )
    op.add_column(
        "question_lang_version",
        sa.Column("mcOptions", sa.Text(collation="utf8mb4_general_ci"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_lang_version", "mcOptions")
    op.drop_column("question_lang_version", "questionText")
    op.drop_column("question", "mcOptions")
    op.drop_column("question", "questionText")
    # ### end Alembic commands ###
