"""Added newReferrals column

Revision ID: 3bfa752b60d2
Revises: 0363083ecb2c
Create Date: 2021-10-25 16:12:50.803636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfa752b60d2'
down_revision = '0363083ecb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthfacility', sa.Column('newReferrals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('healthfacility', 'newReferrals')
    # ### end Alembic commands ###
