"""new covid reading changes

Revision ID: 3d49263fe82c
Revises: a1913287ffaf
Create Date: 2020-07-24 01:30:48.727157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d49263fe82c'
down_revision = 'a1913287ffaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followup', 'followupNeeded',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('patient', sa.Column('householdNumber', sa.String(length=50), nullable=True))
    op.alter_column('patient', 'isPregnant',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('reading', sa.Column('oxygenSaturation', sa.Integer(), nullable=True))
    op.add_column('reading', sa.Column('respiratoryRate', sa.Integer(), nullable=True))
    op.add_column('reading', sa.Column('temperature', sa.Integer(), nullable=True))
    op.alter_column('reading', 'isFlaggedForFollowup',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('referral', 'isAssessed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral', 'isAssessed',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('reading', 'isFlaggedForFollowup',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('reading', 'temperature')
    op.drop_column('reading', 'respiratoryRate')
    op.drop_column('reading', 'oxygenSaturation')
    op.alter_column('patient', 'isPregnant',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('patient', 'householdNumber')
    op.alter_column('followup', 'followupNeeded',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
