"""Change role to string

Revision ID: 429420bdbb6c
Revises: d1264f0574c2
Create Date: 2021-03-20 00:06:25.118093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '429420bdbb6c'
down_revision = 'd1264f0574c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('VHT', 'HCW', 'ADMIN', 'CHO'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('VHT', 'HCW', 'ADMIN', 'CHO'),
               existing_nullable=True)
    # ### end Alembic commands ###
