"""Make question units nullable

Revision ID: 45_c2893bc8d86e
Revises: 44_cd95dad8b17b
Create Date: 2022-03-18 04:37:23.532634

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "45_c2893bc8d86e"
down_revision = "44_cd95dad8b17b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("question", "units", existing_type=mysql.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("question", "units", existing_type=mysql.TEXT(), nullable=False)
    # ### end Alembic commands ###
