"""remove role tables

Revision ID: 46d3d2542f6a
Revises: ea8fb2a0822b
Create Date: 2021-03-26 00:47:28.607425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "46d3d2542f6a"
down_revision = "ea8fb2a0822b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userrole")
    op.drop_table("role")
    op.alter_column(
        "patient",
        "gestationalAgeUnit",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.Enum("MONTHS", "WEEKS", "DAYS", name="gestationalageunitenum"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patient",
        "gestationalAgeUnit",
        existing_type=sa.Enum("MONTHS", "WEEKS", "DAYS", name="gestationalageunitenum"),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.create_table(
        "role",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("name", mysql.ENUM("VHT", "HCW", "ADMIN", "CHO"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "userrole",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "userId",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "roleId",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["roleId"], ["role.id"], name="userrole_ibfk_1"),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], name="userrole_ibfk_2"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
