"""
SMS Relay request number changes

Revision ID: 4_4de9e2572bb1
Revises: 3_f3f6a6a9a6f5
Create Date: 2025-03-25 19:07:51.845125

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4_4de9e2572bb1"
down_revision = "3_f3f6a6a9a6f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_sms_relay_request_number_user_id_user",
        "sms_relay_request_number",
        type_="foreignkey",
    )
    op.drop_index(
        "uq_sms_relay_request_number_user_id", table_name="sms_relay_request_number"
    )
    op.drop_column("sms_relay_request_number", "user_id")
    op.add_column(
        "sms_relay_request_number",
        sa.Column("phone_number", sa.String(length=20), nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_sms_relay_request_number_phone_number"),
        "sms_relay_request_number",
        ["phone_number"],
    )
    op.create_foreign_key(
        op.f("fk_sms_relay_request_number_phone_number_user_phone_number"),
        "sms_relay_request_number",
        "user_phone_number",
        ["phone_number"],
        ["phone_number"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sms_relay_request_number",
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_sms_relay_request_number_phone_number_user_phone_number"),
        "sms_relay_request_number",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_sms_relay_request_number_user_id_user",
        "sms_relay_request_number",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("uq_sms_relay_request_number_phone_number"),
        "sms_relay_request_number",
        type_="unique",
    )
    op.create_index(
        "uq_sms_relay_request_number_user_id",
        "sms_relay_request_number",
        ["user_id"],
        unique=False,
    )
    op.drop_column("sms_relay_request_number", "phone_number")
    # ### end Alembic commands ###
