"""
move sms request numbers to user phone numbers

Revision ID: 4_5aabd60944dd
Revises: 3_f3f6a6a9a6f5
Create Date: 2025-04-09 01:24:03.444259

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4_5aabd60944dd"
down_revision = "3_f3f6a6a9a6f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_sms_relay_request_number_user_id_user",
        "sms_relay_request_number",
        type_="foreignkey",
    )
    op.drop_index(
        "uq_sms_relay_request_number_user_id", table_name="sms_relay_request_number"
    )
    op.drop_table("sms_relay_request_number")
    op.add_column(
        "user_phone_number",
        sa.Column("expected_request_number", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_phone_number", "expected_request_number")
    op.create_table(
        "sms_relay_request_number",
        sa.Column("id", mysql.VARCHAR(length=50), nullable=False),
        sa.Column(
            "expected_request_number",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="fk_sms_relay_request_number_user_id_user",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "uq_sms_relay_request_number_user_id",
        "sms_relay_request_number",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
