"""Add foreign key constraint to patientID in FollowUp

Revision ID: 4cffa05c40e7
Revises: 1029b5bb3354
Create Date: 2022-02-06 02:22:42.343114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cffa05c40e7'
down_revision = '1029b5bb3354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followup', 'patientId',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'followup', 'patient', ['patientId'], ['patientId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followup', type_='foreignkey')
    op.alter_column('followup', 'patientId',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
