"""add form and form template models

Revision ID: 5161a368f64c
Revises: 227cf4f3fa93
Create Date: 2022-03-09 07:51:44.511516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5161a368f64c"
down_revision = "227cf4f3fa93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("dateCreated", sa.BigInteger(), nullable=False),
        sa.Column("createdBy", sa.Integer(), nullable=True),
        sa.Column("lastEdited", sa.BigInteger(), nullable=False),
        sa.Column("lastEditedBy", sa.Integer(), nullable=True),
        sa.Column("questions", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "form",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patientId", sa.String(length=50), nullable=False),
        sa.Column("formTemplateId", sa.Integer(), nullable=False),
        sa.Column("dateCreated", sa.BigInteger(), nullable=False),
        sa.Column("createdBy", sa.Integer(), nullable=True),
        sa.Column("lastEdited", sa.BigInteger(), nullable=False),
        sa.Column("lastEditedBy", sa.Integer(), nullable=True),
        sa.Column("questions", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["formTemplateId"], ["form_template.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["patientId"], ["patient.patientId"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form")
    op.drop_table("form_template")
    # ### end Alembic commands ###
