"""question type change to tmp type

Revision ID: 58_152027798b6f
Revises: 57_e6f5494b9217
Create Date: 2022-04-06 09:36:39.232683

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "58_152027798b6f"
down_revision = "57_e6f5494b9217"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "questionType",
        existing_type=mysql.ENUM(
            "INTEGER",
            "DECIMAL",
            "STRING",
            "MULTIPLE_CHOICE",
            "MULTIPLE_SELECT",
            "DATE",
            "TIME",
            "DATETIME",
        ),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "questionType",
        existing_type=sa.Text(),
        type_=mysql.ENUM(
            "INTEGER",
            "DECIMAL",
            "STRING",
            "MULTIPLE_CHOICE",
            "MULTIPLE_SELECT",
            "DATE",
            "TIME",
            "DATETIME",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
