"""referral remove vital sign

Revision ID: 59a399303ecb
Revises: 8341fdf3f993
Create Date: 2022-02-20 05:35:15.167928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "59a399303ecb"
down_revision = "8341fdf3f993"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referral", "vitalSign")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral",
        sa.Column(
            "vitalSign",
            mysql.ENUM(
                "NONE", "GREEN", "YELLOW_UP", "YELLOW_DOWN", "RED_UP", "RED_DOWN"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
