"""Create tables from rule group, workflow template, workflow classification, template step, and step branch

Revision ID: 5_2f6d68ecb427
Revises: 4_5aabd60944dd
Create Date: 2025-06-13 22:19:35.473782

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5_2f6d68ecb427"
down_revision = "4_5aabd60944dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_group",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("logic", sa.Text(), nullable=True),
        sa.Column("rules", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_group")),
    )
    op.create_table(
        "workflow_classification",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_classification")),
    )
    op.create_index(
        op.f("ix_workflow_classification_name"),
        "workflow_classification",
        ["name"],
        unique=False,
    )
    op.create_table(
        "workflow_template",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("last_edited", sa.DateTime(), nullable=True),
        sa.Column("last_edited_by", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("classification_id", sa.String(length=50), nullable=True),
        sa.Column("initial_conditions", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["classification_id"],
            ["workflow_classification.id"],
            name=op.f("fk_workflow_template_classification_id_workflow_classification"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["initial_conditions"],
            ["rule_group.id"],
            name=op.f("fk_workflow_template_initial_conditions_rule_group"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_template")),
    )
    op.create_index(
        op.f("ix_workflow_template_name"), "workflow_template", ["name"], unique=False
    )
    op.create_table(
        "workflow_template_step",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("expected_completion", sa.DateTime(), nullable=True),
        sa.Column("last_edited", sa.DateTime(), nullable=False),
        sa.Column("last_edited_by", sa.Text(), nullable=False),
        sa.Column("conditions", sa.String(length=50), nullable=True),
        sa.Column("form_id", sa.String(length=50), nullable=False),
        sa.Column("workflow_template_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["conditions"],
            ["rule_group.id"],
            name=op.f("fk_workflow_template_step_conditions_rule_group"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form_template.id"],
            name=op.f("fk_workflow_template_step_form_id_form_template"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_template_id"],
            ["workflow_template.id"],
            name=op.f(
                "fk_workflow_template_step_workflow_template_id_workflow_template"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_template_step")),
    )
    op.create_index(
        op.f("ix_workflow_template_step_name"),
        "workflow_template_step",
        ["name"],
        unique=False,
    )
    op.create_table(
        "workflow_template_step_branch",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("target_step_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.String(length=50), nullable=False),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["condition"],
            ["rule_group.id"],
            name=op.f("fk_workflow_template_step_branch_condition_rule_group"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["workflow_template_step.id"],
            name=op.f(
                "fk_workflow_template_step_branch_step_id_workflow_template_step"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_template_step_branch")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_template_step_branch")
    op.drop_index(
        op.f("ix_workflow_template_step_name"), table_name="workflow_template_step"
    )
    op.drop_table("workflow_template_step")
    op.drop_index(op.f("ix_workflow_template_name"), table_name="workflow_template")
    op.drop_table("workflow_template")
    op.drop_index(
        op.f("ix_workflow_classification_name"), table_name="workflow_classification"
    )
    op.drop_table("workflow_classification")
    op.drop_table("rule_group")
    # ### end Alembic commands ###
