"""empty message

Revision ID: 5bd241bc95c4
Revises: 2c7e8d1996af
Create Date: 2022-06-07 02:07:50.344319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd241bc95c4'
down_revision = '2c7e8d1996af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_form_template_name', table_name='form_template')
    op.create_index(op.f('ix_form_template_name'), 'form_template', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_template_name'), table_name='form_template')
    op.create_index('ix_form_template_name', 'form_template', ['name'], unique=False)
    # ### end Alembic commands ###
