"""referral add vital_sign field

Revision ID: 66168c667895
Revises: b62ebe3bee7a
Create Date: 2022-02-17 07:08:50.039631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66168c667895'
down_revision = 'b62ebe3bee7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('vitalSign', sa.Enum('NONE', 'GREEN', 'YELLOW_UP', 'YELLOW_DOWN', 'RED_UP', 'RED_DOWN', name='trafficlightenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral', 'vitalSign')
    # ### end Alembic commands ###
