"""change question min max type to float form add lang field

Revision ID: 66296a0f5d6f
Revises: c7f274e43562
Create Date: 2022-04-06 04:21:07.399583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "66296a0f5d6f"
down_revision = "c7f274e43562"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form", sa.Column("lang", sa.Text(), nullable=False))
    op.alter_column(
        "question",
        "numMin",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "question",
        "numMax",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.Float(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "numMax",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=True,
    )
    op.alter_column(
        "question",
        "numMin",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=True,
    )
    op.drop_column("form", "lang")
    # ### end Alembic commands ###
