"""empty message

Revision ID: 690e8766e4ac
Revises: ced944a17e66
Create Date: 2020-02-22 12:07:57.000279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690e8766e4ac'
down_revision = 'ced944a17e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('urineTestBlood', sa.String(length=5), nullable=True))
    op.add_column('reading', sa.Column('urineTestGlu', sa.String(length=5), nullable=True))
    op.add_column('reading', sa.Column('urineTestLeuc', sa.String(length=5), nullable=True))
    op.add_column('reading', sa.Column('urineTestNit', sa.String(length=5), nullable=True))
    op.add_column('reading', sa.Column('urineTestPro', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'urineTestPro')
    op.drop_column('reading', 'urineTestNit')
    op.drop_column('reading', 'urineTestLeuc')
    op.drop_column('reading', 'urineTestGlu')
    op.drop_column('reading', 'urineTestBlood')
    # ### end Alembic commands ###
