"""change referral vital sign to not nullable

Revision ID: 69805f277d06
Revises: 66168c667895
Create Date: 2022-02-18 09:34:53.244762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "69805f277d06"
down_revision = "66168c667895"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "referral",
        "vitalSign",
        existing_type=mysql.ENUM(
            "NONE", "GREEN", "YELLOW_UP", "YELLOW_DOWN", "RED_UP", "RED_DOWN"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "referral",
        "vitalSign",
        existing_type=mysql.ENUM(
            "NONE", "GREEN", "YELLOW_UP", "YELLOW_DOWN", "RED_UP", "RED_DOWN"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
