"""
Rename attribute names for some models

Revision ID: 6_e2a9df49ff6e
Revises: 5_2f6d68ecb427
Create Date: 2025-06-16 03:54:40.833648

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6_e2a9df49ff6e"
down_revision = "5_2f6d68ecb427"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template",
        sa.Column("initial_condition_id", sa.String(length=50), nullable=True),
    )
    op.drop_constraint(
        "fk_workflow_template_initial_conditions_rule_group",
        "workflow_template",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_workflow_template_initial_condition_id_rule_group"),
        "workflow_template",
        "rule_group",
        ["initial_condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workflow_template", "initial_conditions")
    op.add_column(
        "workflow_template_step",
        sa.Column("condition_id", sa.String(length=50), nullable=True),
    )
    op.drop_constraint(
        "fk_workflow_template_step_conditions_rule_group",
        "workflow_template_step",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_workflow_template_step_condition_id_rule_group"),
        "workflow_template_step",
        "rule_group",
        ["condition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workflow_template_step", "conditions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_template_step",
        sa.Column("conditions", mysql.VARCHAR(length=50), nullable=True),
    )
    op.drop_constraint(
        op.f("fk_workflow_template_step_condition_id_rule_group"),
        "workflow_template_step",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_workflow_template_step_conditions_rule_group",
        "workflow_template_step",
        "rule_group",
        ["conditions"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workflow_template_step", "condition_id")
    op.add_column(
        "workflow_template",
        sa.Column("initial_conditions", mysql.VARCHAR(length=50), nullable=True),
    )
    op.drop_constraint(
        op.f("fk_workflow_template_initial_condition_id_rule_group"),
        "workflow_template",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_workflow_template_initial_conditions_rule_group",
        "workflow_template",
        "rule_group",
        ["initial_conditions"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("workflow_template", "initial_condition_id")
    # ### end Alembic commands ###
