"""empty message

Revision ID: 713444f3b6c5
Revises: 711f817125f9
Create Date: 2020-07-16 01:01:13.121254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '713444f3b6c5'
down_revision = '711f817125f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'gestationalAgeValue')
    op.drop_column('patient', 'gestationalAgeUnit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('gestationalAgeUnit', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('patient', sa.Column('gestationalAgeValue', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
