"""empty message

Revision ID: 760c99261b86
Revises: 3d7d77465333
Create Date: 2019-11-23 23:51:23.004337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "760c99261b86"
down_revision = "3d7d77465333"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "followup", sa.Column("dateAssessed", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "followup", sa.Column("healthcareWorkerId", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "followup", "user", ["healthcareWorkerId"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "followup", type_="foreignkey")
    op.drop_column("followup", "healthcareWorkerId")
    op.drop_column("followup", "dateAssessed")
    # ### end Alembic commands ###
