"""removed the COVID-19 columns from the readings table

Revision ID: 7734770efb74
Revises: 3a4b8033a6d9
Create Date: 2021-02-02 02:09:03.946579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7734770efb74'
down_revision = '3a4b8033a6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'temperature')
    op.drop_column('reading', 'respiratoryRate')
    op.drop_column('reading', 'oxygenSaturation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('oxygenSaturation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reading', sa.Column('respiratoryRate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reading', sa.Column('temperature', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
