"""
Change 'last_edited_by' field to a foreign key for workflow templates and template steps, change date attributes to BigInteger

Revision ID: 7_8524afee47c9
Revises: 6_e2a9df49ff6e
Create Date: 2025-06-16 22:24:10.222302

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7_8524afee47c9"
down_revision = "6_e2a9df49ff6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_template",
        "date_created",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_template",
        "last_edited",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        nullable=False,
    )
    op.alter_column(
        "workflow_template",
        "last_edited_by",
        existing_type=mysql.TEXT(),
        type_=sa.Integer(),
        nullable=True,
    )
    op.create_foreign_key(
        op.f("fk_workflow_template_last_edited_by_user"),
        "workflow_template",
        "user",
        ["last_edited_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "workflow_template_step",
        "expected_completion",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "workflow_template_step",
        "last_edited",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_template_step",
        "last_edited_by",
        existing_type=mysql.TEXT(),
        type_=sa.Integer(),
        nullable=True,
    )
    op.create_foreign_key(
        op.f("fk_workflow_template_step_last_edited_by_user"),
        "workflow_template_step",
        "user",
        ["last_edited_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workflow_template_step_last_edited_by_user"),
        "workflow_template_step",
        type_="foreignkey",
    )
    op.alter_column(
        "workflow_template_step",
        "last_edited_by",
        existing_type=sa.Integer(),
        type_=mysql.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "workflow_template_step",
        "last_edited",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_template_step",
        "expected_completion",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("fk_workflow_template_last_edited_by_user"),
        "workflow_template",
        type_="foreignkey",
    )
    op.alter_column(
        "workflow_template",
        "last_edited_by",
        existing_type=sa.Integer(),
        type_=mysql.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "workflow_template",
        "last_edited",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "workflow_template",
        "date_created",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
