"""
remove redundant question_id

Revision ID: 82_4f4c1a347eab
Revises: 5641d7c32ebd
Create Date: 2025-01-03 20:58:19.103744

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "82_4f4c1a347eab"
down_revision = "5641d7c32ebd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("question_id", mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
