"""referral add vital sign

Revision ID: 8341fdf3f993
Revises: 69805f277d06
Create Date: 2022-02-18 10:19:02.729681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8341fdf3f993'
down_revision = 'b62ebe3bee7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('vitalSign', sa.Enum('NONE', 'GREEN', 'YELLOW_UP', 'YELLOW_DOWN', 'RED_UP', 'RED_DOWN', name='trafficlightenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral', 'vitalSign')
    # ### end Alembic commands ###
