"""
change healthfacility to use snake case

Revision ID: 84_a78c469e5207
Revises: 83_db1699b82aa0
Create Date: 2024-11-03 20:04:12.869626

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "84_a78c469e5207"
down_revision = "83_db1699b82aa0"
branch_labels = None
depends_on = None


def upgrade():
    # Rename table.
    op.rename_table(old_table_name="healthfacility",
                    new_table_name="health_facility")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table(old_table_name="health_facility",
                    new_table_name="healthfacility")
    # ### end Alembic commands ###
