"""add sub column to user

Revision ID: 86_d9153b6a07c3
Revises: 85_b06fe66ca2b4
Create Date: 2024-11-04 02:54:52.942461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86_d9153b6a07c3'
down_revision = '85_b06fe66ca2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sub', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'user', ['sub'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'sub')
    # ### end Alembic commands ###
