"""add form template model and add more form model fields

Revision ID: 88f54cec6966
Revises: dbd9bcf53db8
Create Date: 2022-03-08 11:23:47.714552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "88f54cec6966"
down_revision = "dbd9bcf53db8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("dateCreated", sa.BigInteger(), nullable=False),
        sa.Column("createdBy", sa.Integer(), nullable=True),
        sa.Column("lastEdited", sa.BigInteger(), nullable=False),
        sa.Column("lastEditedBy", sa.Integer(), nullable=True),
        sa.Column("questions", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("form", sa.Column("formTemplateId", sa.Integer(), nullable=False))
    op.add_column("form", sa.Column("dateCreated", sa.BigInteger(), nullable=False))
    op.add_column("form", sa.Column("createdBy", sa.Integer(), nullable=True))
    op.add_column("form", sa.Column("lastEdited", sa.BigInteger(), nullable=False))
    op.add_column("form", sa.Column("lastEditedBy", sa.Integer(), nullable=True))
    op.add_column("form", sa.Column("questions", sa.Text(), nullable=False))
    op.create_foreign_key(
        None, "form", "form_template", ["formTemplateId"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("form", "form")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form", sa.Column("form", mysql.TEXT(), nullable=False))
    op.drop_constraint(None, "form", type_="foreignkey")
    op.drop_column("form", "questions")
    op.drop_column("form", "lastEditedBy")
    op.drop_column("form", "lastEdited")
    op.drop_column("form", "createdBy")
    op.drop_column("form", "dateCreated")
    op.drop_column("form", "formTemplateId")
    op.drop_table("form_template")
    # ### end Alembic commands ###
