"""
Create model for workflow instances

Revision ID: 8_1d8f10250319
Revises: 7_8524afee47c9
Create Date: 2025-06-17 22:02:55.857017

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8_1d8f10250319"
down_revision = "7_8524afee47c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_instance",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("last_edited", sa.DateTime(), nullable=True),
        sa.Column("completion_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("workflow_template_id", sa.String(length=50), nullable=True),
        sa.Column("last_edited_by", sa.Integer(), nullable=True),
        sa.Column("patient_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_edited_by"],
            ["user.id"],
            name=op.f("fk_workflow_instance_last_edited_by_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
            name=op.f("fk_workflow_instance_patient_id_patient"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_template_id"],
            ["workflow_template.id"],
            name=op.f("fk_workflow_instance_workflow_template_id_workflow_template"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_instance")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_instance")
    # ### end Alembic commands ###
