"""Specifying role in users table

Revision ID: 9537fdf73db1
Revises: 7734770efb74
Create Date: 2021-03-19 18:39:30.457088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9537fdf73db1'
down_revision = '7734770efb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'roleSpecified',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('VHT', 'HCW', 'ADMIN', 'CHO', name='roleenum'),
               existing_nullable=True)
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('user', 'roleSpecified',
               existing_type=sa.Enum('VHT', 'HCW', 'ADMIN', 'CHO', name='roleenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
