"""Add patientId to FollowUp

Revision ID: 97473443e1fa
Revises: 1029b5bb3354
Create Date: 2022-02-06 03:00:56.200530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97473443e1fa'
down_revision = '1029b5bb3354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup', sa.Column('patientId', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followup', 'patientId')
    # ### end Alembic commands ###
