"""Remove pregnancy, drug, and medical info from patient table

Revision ID: 97ca57c727de
Revises: 0363083ecb2c
Create Date: 2021-06-23 00:20:59.090745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "97ca57c727de"
down_revision = "0363083ecb2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patient", "gestationalAgeUnit")
    op.drop_column("patient", "medicalHistory")
    op.drop_column("patient", "gestationalTimestamp")
    op.drop_column("patient", "drugHistory")
    op.drop_column("patient", "isPregnant")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patient",
        sa.Column(
            "isPregnant",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column("patient", sa.Column("drugHistory", mysql.TEXT(), nullable=True))
    op.add_column(
        "patient",
        sa.Column(
            "gestationalTimestamp",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column("patient", sa.Column("medicalHistory", mysql.TEXT(), nullable=True))
    op.add_column(
        "patient",
        sa.Column(
            "gestationalAgeUnit", mysql.ENUM("MONTHS", "WEEKS", "DAYS"), nullable=True
        ),
    )
    # ### end Alembic commands ###
