"""
Change date attributes for workflow instance, create workflow instance step model

Revision ID: 9_54251029538f
Revises: 8_1d8f10250319
Create Date: 2025-06-18 19:59:32.667494

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9_54251029538f"
down_revision = "8_1d8f10250319"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_instance_step",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("last_edited", sa.BigInteger(), nullable=False),
        sa.Column("expected_completion", sa.BigInteger(), nullable=True),
        sa.Column("completion_date", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("form_id", sa.String(length=50), nullable=False),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column("workflow_instance_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["user.id"],
            name=op.f("fk_workflow_instance_step_assigned_to_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form.id"],
            name=op.f("fk_workflow_instance_step_form_id_form"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_instance_id"],
            ["workflow_instance.id"],
            name=op.f(
                "fk_workflow_instance_step_workflow_instance_id_workflow_instance"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_instance_step")),
    )
    op.alter_column(
        "workflow_instance",
        "start_date",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_instance",
        "last_edited",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        nullable=False,
    )
    op.alter_column(
        "workflow_instance",
        "completion_date",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_instance",
        "completion_date",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        existing_nullable=True,
    )
    op.alter_column(
        "workflow_instance",
        "last_edited",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        nullable=True,
    )
    op.alter_column(
        "workflow_instance",
        "start_date",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.drop_table("workflow_instance_step")
    # ### end Alembic commands ###
