"""empty message

Revision ID: 9e78d55f356e
Revises: 8c1d925451fe
Create Date: 2020-02-26 11:29:56.788896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e78d55f356e'
down_revision = '8c1d925451fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup', sa.Column('dateReviewNeeded', sa.Date(), nullable=True))
    op.add_column('followup', sa.Column('followupNeeded', sa.Boolean(), nullable=True))
    op.add_column('followup', sa.Column('medicationPrescribed', sa.Text(), nullable=True))
    op.add_column('followup', sa.Column('specialInvestigations', sa.Text(), nullable=True))
    op.add_column('patient', sa.Column('dob', sa.Date(), nullable=True))
    op.drop_column('patient', 'tank')
    op.drop_column('patient', 'block')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('block', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('patient', sa.Column('tank', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('patient', 'dob')
    op.drop_column('followup', 'specialInvestigations')
    op.drop_column('followup', 'medicationPrescribed')
    op.drop_column('followup', 'followupNeeded')
    op.drop_column('followup', 'dateReviewNeeded')
    # ### end Alembic commands ###
