"""empty message

Revision ID: a1913287ffaf
Revises: d41dc6eb7f5d
Create Date: 2020-07-16 17:12:47.556117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1913287ffaf'
down_revision = 'd41dc6eb7f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followup', 'dateAssessed',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('patient', 'dob',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('reading', 'dateRecheckVitalsNeeded',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('reading', 'dateTimeTaken',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('referral', 'dateReferred',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral', 'dateReferred',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('reading', 'dateTimeTaken',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('reading', 'dateRecheckVitalsNeeded',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('patient', 'dob',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('followup', 'dateAssessed',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
