"""empty message

Revision ID: ab46b58637fa
Revises: ced944a17e66
Create Date: 2020-02-25 23:44:23.254257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab46b58637fa'
down_revision = 'ced944a17e66'
branch_labels = None
depends_on = None
DateTime()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup', sa.Column('dateTimeReviewNeeded', sa.DateTime(), nullable=True))
    op.add_column('followup', sa.Column('followupNeeded', sa.Boolean(), nullable=True))
    op.add_column('followup', sa.Column('medicationPrescribed', sa.Text(), nullable=True))
    op.add_column('followup', sa.Column('specialInvestigations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followup', 'specialInvestigations')
    op.drop_column('followup', 'medicationPrescribed')
    op.drop_column('followup', 'followupNeeded')
    op.drop_column('followup', 'dateTimeReviewNeeded')
    # ### end Alembic commands ###
