"""Add foreign key to patientId in FollowUp

Revision ID: ab7829f42f36
Revises: 97473443e1fa
Create Date: 2022-02-06 03:04:25.430487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab7829f42f36'
down_revision = '97473443e1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followup', 'patientId',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'followup', 'patient', ['patientId'], ['patientId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followup', type_='foreignkey')
    op.alter_column('followup', 'patientId',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
