"""change template name to unique, index

Revision ID: aeaf3db56ab1
Revises: 15ba72e0ecaa
Create Date: 2022-04-18 05:28:24.883899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeaf3db56ab1'
down_revision = '15ba72e0ecaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_template', 'name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_form_template_name'), 'form_template', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_template_name'), table_name='form_template')
    op.alter_column('form_template', 'name',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
