"""empty message

Revision ID: aff6c3462162
Revises: 9e78d55f356e
Create Date: 2020-03-04 00:20:27.553996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff6c3462162'
down_revision = '9e78d55f356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_facility',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patientId', sa.String(length=50), nullable=False),
    sa.Column('healthFacilityName', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['healthFacilityName'], ['healthfacility.healthFacilityName'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patient.patientId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patientId', 'healthFacilityName', name='no_duplicate_patient_facility')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_facility')
    # ### end Alembic commands ###
