"""Remove phoneNumber attribute from User table
Revision ID: b52e9a02aaff
Revises: 223e648ca151
Create Date: 2023-07-22 22:17:25.566719
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b52e9a02aaff"
down_revision = "223e648ca151"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phoneNumber")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("phoneNumber", mysql.VARCHAR(length=15), nullable=True)
    )
    # ### end Alembic commands ###

