"""empty message

Revision ID: b6e2a0d44da8
Revises: 0f5578c0f6bb
Create Date: 2019-09-28 15:41:26.971755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e2a0d44da8'
down_revision = '0f5578c0f6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_ibfk_1', 'patient', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('patient_ibfk_1', 'patient', 'village', ['villageNumber'], ['villageNumber'])
    # ### end Alembic commands ###
