"""Add sms relay server phone numbers table

Revision ID: bef7a571db37
Revises: 1ca32c9ac887
Create Date: 2023-11-15 04:04:02.329774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bef7a571db37"
down_revision = "1ca32c9ac887"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relay_server_phone_number",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(length=50), nullable=True),
        sa.Column("lastReceived", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relay_server_phone_number")
    # ### end Alembic commands ###
