"""empty message

Revision ID: c2068f6f21d0
Revises: 2c7e8d1996af
Create Date: 2022-06-07 05:34:22.857646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2068f6f21d0'
down_revision = '2c7e8d1996af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template', sa.Column('archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_template', 'archived')
    # ### end Alembic commands ###
