"""Decouple FollowUp table from Reading table

Revision ID: c2df1dcd9256
Revises: daacd2c90e9e
Create Date: 2022-02-01 04:22:51.813162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2df1dcd9256'
down_revision = 'daacd2c90e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('followup_ibfk_2', 'followup', type_='foreignkey')
    op.drop_column('followup', 'readingId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup', sa.Column('readingId', mysql.VARCHAR(length=50), nullable=False))
    op.create_foreign_key('followup_ibfk_2', 'followup', 'reading', ['readingId'], ['readingId'])
    # ### end Alembic commands ###
