"""nullable associations

Revision ID: cc4478373908
Revises: 7904e9f1d50e
Create Date: 2020-07-19 16:11:29.574908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cc4478373908"
down_revision = "7904e9f1d50e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patient_associations",
        sa.Column("id", sa.Integer(), nullable=False),
    )

    # Drop foreign key constraints
    op.execute(
        """
        ALTER TABLE patient_associations 
        DROP FOREIGN KEY patient_associations_ibfk_1
        """
    )
    op.execute(
        """
        ALTER TABLE patient_associations 
        DROP FOREIGN KEY patient_associations_ibfk_2
        """
    )
    op.execute(
        """
        ALTER TABLE patient_associations 
        DROP FOREIGN KEY patient_associations_ibfk_3
        """
    )

    # Drop primary key constraint
    op.execute("ALTER TABLE patient_associations DROP PRIMARY KEY")

    # Add new primary key constraint
    op.execute(
        """
        ALTER TABLE patient_associations 
        ADD CONSTRAINT patient_associations_pk PRIMARY KEY (id)
        """
    )

    # Make it auto-increment
    op.execute(
        """
        ALTER TABLE patient_associations
        MODIFY id INTEGER NOT NULL AUTO_INCREMENT
        """
    )

    # Add back foreign key constraints
    op.execute(
        """
        ALTER TABLE patient_associations
        ADD CONSTRAINT patient_associations_ibfk_1
        FOREIGN KEY (healthFacilityName) 
        REFERENCES healthfacility (healthFacilityName)
        ON DELETE CASCADE
        """
    )
    # If patient is deleted, we should delete all associations for them
    op.execute(
        """
        ALTER TABLE patient_associations
        ADD CONSTRAINT patient_associations_ibfk_2
        FOREIGN KEY (patientId) 
        REFERENCES patient (patientId) 
        ON DELETE CASCADE
        """
    )
    op.execute(
        """
        ALTER TABLE patient_associations
        ADD CONSTRAINT patient_associations_ibfk_3
        FOREIGN KEY (userId) 
        REFERENCES user (id)
        ON DELETE CASCADE
        """
    )

    op.alter_column(
        "patient_associations",
        "healthFacilityName",
        existing_type=mysql.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "patient_associations",
        "userId",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patient_associations",
        "userId",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    op.alter_column(
        "patient_associations",
        "healthFacilityName",
        existing_type=mysql.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_column("patient_associations", "id")

    op.execute(
        """
        ALTER TABLE patient_associations 
        ADD CONSTRAINT patient_associations_pk 
        PRIMARY KEY (patientId, healthFacilityName, userId)
        """
    )
    # ### end Alembic commands ###
