"""Rename role column

Revision ID: d1264f0574c2
Revises: 9537fdf73db1
Create Date: 2021-03-19 18:40:53.246431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1264f0574c2'
down_revision = '9537fdf73db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('VHT', 'HCW', 'ADMIN', 'CHO', name='roleenum'), nullable=True))
    op.drop_column('user', 'roleSpecified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roleSpecified', mysql.ENUM('VHT', 'HCW', 'ADMIN', 'CHO'), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
