"""add form table

Revision ID: dbd9bcf53db8
Revises: 227cf4f3fa93
Create Date: 2022-03-05 17:31:25.204434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd9bcf53db8'
down_revision = '227cf4f3fa93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form', sa.Text(), nullable=False),
    sa.Column('patientId', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patient.patientId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
