"""empty message

Revision ID: dccc985a0357
Revises: b744b32f117e
Create Date: 2021-06-15 01:53:06.873546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccc985a0357'
down_revision = 'b744b32f117e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pregnancy_history', sa.Column('defaultTimeUnit', sa.Enum('MONTHS', 'WEEKS', name='gestationalageunitenum'), nullable=True))
    op.add_column('pregnancy_history', sa.Column('lastEdited', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pregnancy_history', 'lastEdited')
    op.drop_column('pregnancy_history', 'defaultTimeUnit')
    # ### end Alembic commands ###
