"""question type change to new question type enum

Revision ID: f0abb9a3e931
Revises: 152027798b6f
Create Date: 2022-04-06 09:39:43.602553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0abb9a3e931'
down_revision = '152027798b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'questionType',
               existing_type=mysql.TEXT(),
               type_=sa.Enum('INTEGER', 'DECIMAL', 'STRING', 'MULTIPLE_CHOICE', 'MULTIPLE_SELECT', 'DATE', 'TIME', 'DATETIME', 'CATEGORY', name='questiontypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'questionType',
               existing_type=sa.Enum('INTEGER', 'DECIMAL', 'STRING', 'MULTIPLE_CHOICE', 'MULTIPLE_SELECT', 'DATE', 'TIME', 'DATETIME', 'CATEGORY', name='questiontypeenum'),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
