"""empty message

Revision ID: f39dd7eac781
Revises: f64d52006db0
Create Date: 2023-07-26 02:56:31.671940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f39dd7eac781"
down_revision = "f64d52006db0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_secret_key",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("secret_Key", sa.String(length=256), nullable=False),
        sa.Column("stale_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_date", sa.DateTime(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sms_secret_key")
    # ### end Alembic commands ###
