"""add classification link and archived tag to form model

Revision ID: f532e4055de0
Revises: 3451c3010032
Create Date: 2022-07-17 09:11:07.686395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f532e4055de0"
down_revision = "3451c3010032"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form", sa.Column("formClassificationId", sa.String(length=50), nullable=True)
    )
    op.add_column("form", sa.Column("archived", sa.Boolean(), nullable=False))
    op.create_foreign_key(
        None,
        "form",
        "form_classification",
        ["formClassificationId"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "form", type_="foreignkey")
    op.drop_column("form", "archived")
    op.drop_column("form", "formClassificationId")
    # ### end Alembic commands ###
